### ISSUE TITLE
How should the proxy server reference users with the protocol?

### ISSUE THREAD

**Issue by JamenMarz** [Tunnelled/Protocol#1]
Right now, the current protocol goes under this basis...

`id` references a row in a table or a value in the memory (depending on the type of request)...  For instance, a request for something user-targeted (e.g. a message) would contain the `id` in which the proxy server has "clusters" of networks associated with.  So, if I had my phone and computer connected to my account, the cluster would contain a IP reference to both of those.  And if someone sends me a message, it gets resolved to both those IPs and echoed to both.

Do you think this should be redesigned? That's currently the basis for anything target-based in the protocol.

**Comment by ThePixelPony** [comment]
It works for me. "Clusters" is making it sound complicated, when in actual fact you're just storing an array of Client objects (or at least that's how I would design it). The "Id" field is good.
The system is good imo.

**Comment by JamenMarz** [comment]
Alright, that's exactly what I thinking.  We'll go under that system then.
